import Providers from "@/utils/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import Navigation from "./home/components/Navigation";
import NavBar from "./home/components/NavBar";
import RaffleNotification from "./components/RaffleNotification";
import Notification from "./components/Notification";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black">
      <Notification />
         {/* @ts-expect-error Server Component */}
        <NavBar />
        
        <RaffleNotification />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
